function Fint = FintEB4DOF(E,Iz,L,in4)
%FintEB4DOF
%    Fint = FintEB4DOF(E,Iz,L,IN4)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Oct-2026 12:26:55

theta1 = in4(2,:);
theta2 = in4(4,:);
v1 = in4(1,:);
v2 = in4(3,:);
t2 = L.^2;
t3 = theta1.*3.0;
t4 = theta2.*3.0;
t5 = v1.*3.0;
t6 = v2.*3.0;
t7 = v1.*6.0;
t8 = v2.*6.0;
t9 = 1.0./L.^3;
t10 = -t6;
t11 = -t8;
t12 = t3+t4;
t13 = t5+t10;
t14 = t7+t11;
t15 = E.*Iz.*L.*t12.*2.0;
t16 = E.*Iz.*t14.*2.0;
t17 = E.*Iz.*L.*t13.*2.0;
t18 = t15+t16;
t19 = t9.*t18;
Fint = [t19,t9.*(t17+E.*Iz.*t2.*(theta1.*2.0+theta2).*2.0),-t19,t9.*(t17+E.*Iz.*t2.*(theta1+theta2.*2.0).*2.0)];
end
