function N = Shapef_EB4DOF(x,L)
%Shapef_EB4DOF
%    N = Shapef_EB4DOF(X,L)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Oct-2026 12:26:55

t2 = x.^2;
t3 = x.^3;
t4 = 1.0./L;
t5 = t4.^2;
t6 = t4.^3;
t7 = t3.*t5;
t8 = t2.*t5.*3.0;
t9 = t3.*t6.*2.0;
N = [-t8+t9+1.0,t7+x-t2.*t4.*2.0,t8-t9,t7-t2.*t4];
end
