function Nvec = ShapefunctionsQ4(Lx,Ly,x,y)
%ShapefunctionsQ4
%    Nvec = ShapefunctionsQ4(Lx,Ly,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    27-Oct-2025 13:18:58

t2 = 1.0./Lx;
t3 = 1.0./Ly;
Nvec = [t2.*x.*(1.6e+1./3.1e+1)+t3.*y.*(2.0e+1./3.1e+1)-t2.*t3.*x.*y.*(5.6e+1./3.1e+1)+2.0e+1./3.1e+1,t2.*x.*(8.0./9.3e+1)+t3.*y.*(1.0e+1./9.3e+1)+t2.*t3.*x.*y.*(3.2e+1./3.1e+1)-7.0./3.1e+1,t2.*x.*(4.0./9.3e+1)-t3.*y.*(8.8e+1./9.3e+1)+t2.*t3.*x.*y.*(1.6e+1./3.1e+1)+1.2e+1./3.1e+1,t2.*x.*(-2.0e+1./3.1e+1)+t3.*y.*(6.0./3.1e+1)+t2.*t3.*x.*y.*(8.0./3.1e+1)+6.0./3.1e+1];
end
