function Nvec = ShapefunctionsQ4(Lx,Ly,x,y)
%ShapefunctionsQ4
%    Nvec = ShapefunctionsQ4(Lx,Ly,X,Y)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    04-Jun-2026 10:16:49

t2 = 1.0./Lx;
t3 = 1.0./Ly;
t4 = (t2.*x)./2.0;
t5 = (t3.*y)./2.0;
t8 = t2.*t3.*x.*y;
t6 = -t4;
t7 = -t5;
t9 = -t8;
Nvec = [t6+t7+t8+1.0./4.0,t4+t7+t9+1.0./4.0,t4+t5+t8+1.0./4.0,t5+t6+t9+1.0./4.0];
end
