function N = Shapef3NodeRod(x,L)
%Shapef3NodeRod
%    N = Shapef3NodeRod(X,L)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    25-Sep-2025 13:04:39

t2 = x.^2;
t3 = 1.0./L;
t4 = t3.^2;
t5 = t2.*t4.*2.0;
N = [t5-t3.*x.*3.0+1.0,t2.*t4.*-4.0+t3.*x.*4.0,t5-t3.*x];
end
