function N = Shapef2NodeRod(x,L)
%Shapef2NodeRod
%    N = Shapef2NodeRod(X,L)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    25-Sep-2025 13:16:52

t2 = 1.0./L;
t3 = t2.*x;
N = [-t3+1.0,t3];
end
