function Mloclumbed = MloclumpedQ4(in1,rho,Lz)
%MloclumpedQ4
%    Mloclumbed = MloclumpedQ4(IN1,RHO,Lz)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    01-Dec-2025 12:54:25

X1 = in1(1,:);
X2 = in1(2,:);
X3 = in1(3,:);
X4 = in1(4,:);
X5 = in1(5,:);
X6 = in1(6,:);
X7 = in1(7,:);
X8 = in1(8,:);
t2 = (X1.*X4)./2.0;
t3 = (X2.*X3)./2.0;
t4 = (X1.*X8)./2.0;
t5 = (X2.*X7)./2.0;
t6 = (X3.*X6)./2.0;
t7 = (X4.*X5)./2.0;
t8 = (X5.*X8)./2.0;
t9 = (X6.*X7)./2.0;
t10 = -t3;
t11 = -t4;
t12 = -t7;
t13 = -t9;
t14 = t2+t5+t6+t8+t10+t11+t12+t13;
t15 = Lz.*rho.*t14;
Mloclumbed = reshape([t15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t15],[8,8]);
end
