function Kloc = KlocEB4DOF(E,Iz,L)
%KlocEB4DOF
%    Kloc = KlocEB4DOF(E,Iz,L)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    13-Oct-2023 12:34:10

t2 = 1.0./L;
t3 = t2.^2;
t4 = t2.^3;
t5 = E.*Iz.*t2.*2.0;
t6 = E.*Iz.*t2.*4.0;
t7 = E.*Iz.*t3.*6.0;
t9 = E.*Iz.*t4.*1.2e+1;
t8 = -t7;
t10 = -t9;
Kloc = reshape([t9,t7,t10,t7,t7,t6,t8,t5,t10,t8,t9,t8,t7,t5,t8,t6],[4,4]);
