function Nvec = ShapefunctionsQ4xi(Lx,Ly,xi,eta)
%ShapefunctionsQ4xi
%    Nvec = ShapefunctionsQ4xi(Lx,Ly,XI,ETA)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    03-Nov-2025 13:43:53

t2 = eta./4.0;
t3 = xi./4.0;
t7 = eta.*xi.*(-1.0./4.0);
t4 = t2.*xi;
t5 = -t2;
t6 = -t3;
Nvec = [t4+t5+t6+1.0./4.0,t3+t5+t7+1.0./4.0,t2+t3+t4+1.0./4.0,t2+t6+t7+1.0./4.0];
end
