function Kloc = KlocRod(A,E,L)
%KLOCROD
%    KLOC = KLOCROD(A,E,L)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    27-Feb-2023 11:27:51

t2 = 1.0./L;
t3 = A.*E.*t2;
t4 = -t3;
Kloc = reshape([t3,t4,t4,t3],[2,2]);
