function Kloc = KlocRod(A,E,L)
%KlocRod
%    Kloc = KlocRod(A,E,L)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-Sep-2026 13:32:03

t2 = 1.0./L;
t3 = A.*E.*t2;
t4 = -t3;
Kloc = reshape([t3,t4,t4,t3],[2,2]);
end
