function Wint = WintRod(u1,u2,A,E,L)
%WintRod
%    Wint = WintRod(U1,U2,A,E,L)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    14-Sep-2026 13:32:03

Wint = (A.*E.*(u1-u2).^2)./(L.*2.0);
end
