function N = Shapef2NodeRod(x,L)
%SHAPEF2NODEROD
%    N = SHAPEF2NODEROD(X,L)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    27-Feb-2023 11:27:50

t2 = 1.0./L;
t3 = t2.*x;
N = [-t3+1.0,t3];
