function Nvec = ShapefunctionsQ4xi(Lx,Ly,xi,eta)
%SHAPEFUNCTIONSQ4XI
%    NVEC = SHAPEFUNCTIONSQ4XI(LX,LY,XI,ETA)

%    This function was generated by the Symbolic Math Toolbox version 8.6.
%    22-Mar-2022 15:42:11

t2 = eta./4.0;
t3 = xi./4.0;
t7 = eta.*xi.*(-1.0./4.0);
t4 = t2.*xi;
t5 = -t2;
t6 = -t3;
Nvec = [t4+t5+t6+1.0./4.0,t3+t5+t7+1.0./4.0,t2+t3+t4+1.0./4.0,t2+t6+t7+1.0./4.0];
