function theta2anal = theta2anal(x,E,I1,I2,L1,L2,F)
%THETA2ANAL
%    THETA2ANAL = THETA2ANAL(X,E,I1,I2,L1,L2,F)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Oct-2026 11:15:45

t2 = L1.^2;
t3 = L1.^3;
t4 = L2.^2;
t5 = L2.^3;
t6 = x.^2;
theta2anal = (F.*t2.*(I1.*t3.*2.0+I1.*t5.*2.0+I1.*L2.*t2.*7.0+I1.*L1.*t4.*6.0-I2.*L2.*t2+I1.*L1.*t6.*2.0+I1.*L2.*t6.*3.0-I1.*t2.*x.*4.0-I1.*t4.*x.*6.0-I1.*L1.*L2.*x.*1.0e+1).*(-1.0./4.0))./(E.*I1.*(I2.*t3+I1.*t5+I2.*L2.*t2.*3.0+I2.*L1.*t4.*3.0));
end
