function v1anal = v1anal(x,E,I1,I2,L1,L2,F)
%V1ANAL
%    V1ANAL = V1ANAL(X,E,I1,I2,L1,L2,F)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Oct-2026 11:15:45

t2 = L1.^2;
t3 = L1.^3;
t4 = L2.^2;
v1anal = (F.*L2.*x.^2.*(I2.*t3.*3.0+I1.*L1.*t4.*6.0+I2.*L2.*t2.*9.0-I2.*t2.*x.*3.0-I1.*t4.*x.*2.0-I2.*L1.*L2.*x.*6.0).*(-1.0./1.2e+1))./(E.*I1.*(I2.*t3+I1.*L2.^3+I2.*L2.*t2.*3.0+I2.*L1.*t4.*3.0));
end
