function v2anal = v2anal(x,E,I1,I2,L1,L2,F)
%V2ANAL
%    V2ANAL = V2ANAL(X,E,I1,I2,L1,L2,F)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Oct-2026 14:33:44

t2 = L1.^2;
t3 = L1.^3;
t4 = L2.^2;
t5 = x.^2;
t6 = I2.*L2.*t2.*3.0;
v2anal = (F.*t2.*(L1+L2-x).*(-t6+I1.*t3.*2.0+I1.*L2.*t2.*7.0+I1.*L1.*t4.*2.0+I1.*L1.*t5.*2.0+I1.*L2.*t5.*3.0-I1.*t2.*x.*4.0-I1.*t4.*x.*6.0-I1.*L1.*L2.*x.*1.0e+1))./(E.*I1.*(t6+I2.*t3+I1.*L2.^3+I2.*L1.*t4.*3.0).*1.2e+1);
end
