function x_v1max = x_v1max(I1,I2,L1,L2)
%X_V1MAX
%    X_V1MAX = X_V1MAX(I1,I2,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Oct-2026 11:15:45

t2 = L1.^2;
t3 = L2.^2;
x_v1max = [0.0;(I2.*L1.^3.*2.0+I1.*L1.*t3.*4.0+I2.*L2.*t2.*6.0)./(I1.*t3.*2.0+I2.*t2.*3.0+I2.*L1.*L2.*6.0)];
end
