function x_v2max = x_v2max(I1,I2,L1,L2)
%X_V2MAX
%    X_V2MAX = X_V2MAX(I1,I2,L1,L2)

%    This function was generated by the Symbolic Math Toolbox version 24.2.
%    05-Oct-2026 14:33:45

t2 = L1.*2.0;
t3 = L2.*3.0;
t4 = L1.^2;
t5 = L2.^2;
t9 = I1.*L1.*L2.*5.0;
t6 = I1.*t2;
t7 = I1.*t3;
t10 = I1.*t5;
t11 = I2.*t4;
t14 = t2+t3;
t8 = L2.*t6;
t12 = L1.*t6;
t13 = L2.*t7;
t15 = t6+t7;
t16 = 1.0./t15;
t17 = t8+t10+t11;
t18 = I1.*L2.*t14.*t17;
t19 = sqrt(t18);
x_v2max = [t16.*(t9+t12+t13+t19);t16.*(t9+t12+t13-t19)];
end
